server:
  context-path: /C4A
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: INFO
  config: classpath:log4j2.xml
spring:
  main:
    web-environment: true
    banner-mode: false
  datasource:
    url: jdbc:postgresql://109.111.225.84:5432/city4age?characterEncoding=utf8&useUnicode=true&currentSchema=city4age_sr
    driver-class-name: org.postgresql.Driver
    username: city4age_srv
    password: cities4Ages
    testWhileIdle: true
    validationQuery: SELECT 1
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        cache.use_second_level_cache: true
        cache.use_query_cache: true
      javax:
        persistence:
          sharedCache:
            mode: ALL